version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_URL= ${DB_URL}
      - DB_USER=  ${DB_USER}
      - DB_PASSWORD= ${DB_PASSWORD}
      - MQ_URL= ${MQ_URL}
      - MQ_USER= ${MQ_USER}
      - MQ_PASSWORD= ${MQ_PASSWORD}
      - SECRET_JWT= ${SECRET_JWT}
      - TIME_JWT= ${TIME_JWT}
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_NAME}
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # para acessar a interface de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_DEFAULT_PASSWORD}
