spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  metrics:
    export:
      azuremonitor:
        enabled: false
  endpoints:
    web:
      exposure:
        include: ''