spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: ""

  metrics:
    export:
      azuremonitor:
        enabled: false

server:
  port: 80 
