name: Azure Web App Deploy - App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build App
        working-directory: Projeto/backend/app
        run: mvn clean package -DskipTests

      - name: Deploy App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-localfarm'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_APP }}
          package: 'Projeto/backend/app/target/app-0.0.1-SNAPSHOT.jar'