name: Azure Web App Deploy - Supplier

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-supplier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Supplier
        working-directory: Projeto/backend/supplier
        run: mvn clean package -DskipTests

      - name: Deploy Supplier
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fornecedor-localfarm'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SUPPLIER }}
          package: Projeto/backend/supplier/target/supplier-0.0.1-SNAPSHOT.jar