name: Azure Web App Deploy - Product

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-product:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Product
        working-directory: Projeto/backend/product
        run: mvn clean package -DskipTests

      - name: Deploy Product
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'produto'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCT }}
          package: Projeto/backend/product/target/product-0.0.1-SNAPSHOT.jar