name: Azure Web App Deploy - Client

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Client
        working-directory: Projeto/backend/client
        run: mvn clean package -DskipTests

      - name: Deploy Client
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cliente-localfarm'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CLIENT }}
          package: Projeto/backend/client/target/client-0.0.1-SNAPSHOT.jar